### PR TITLE
Update all.css: Fixed footer on start page

### PR DESCRIPTION
**Pull request by funeralchris**
I added "min-height: 100%;" to the main.container element to fix the footer on the startpage. The fix doesn't visually affect other pages.

### CODE REVIEW

**Comment by frlan** [comment]
It appears that this moves the footer to a point, where always scrolling is needed.

**Comment by funeralchris** [comment]
This is actually a different bug. The size of the body element is bigger than the contents. I have not yet found the cause for the oversized body element.

Changing "html, body: height: 100%;" in semantic.css:518 to "min-height" changes the page behaviour.

**Comment by funeralchris** [comment]
```
main.main.container {
    margin-top: 5em;
    margin-bottom: 6em;
    min-height: 100%;
```

and

```
#header {
    position: relative;}
```

fixes this behaviour.

**Comment by funeralchris** [comment]
Update: This seems to be the easiest fix:

```
main.main.container {
    margin-top: 5em;
    min-height: calc(100% - 108px);
```

**Comment by enko** [comment]
LGTM

**Comment by frlan** [comment]
Did not solve all issue I had but improves a lot.

**Pull request merged**
